[package]
name = "account_abstraction"
version = "0.0.0"

[addresses]
deployer = "_"

[dependencies]
AptosFramework = { git = "https://github.com/movement-network/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "m1" }
AptosStdlib = { git = "https://github.com/movement-network/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib", rev = "m1" }
