name: "Run SDK E2E tests"
description: |
  Run the SDK E2E tests against Movement testnet

runs:
  using: composite
  steps:
    # Install node and pnpm.
    - uses: actions/setup-node@v4
      with:
        node-version-file: .node-version
        registry-url: "https://registry.npmjs.org"
    - uses: pnpm/action-setup@v4

    # Run package install. If install fails, it probably means the updated lockfile was
    # not included in the commit.
    - run: pnpm install --frozen-lockfile
      shell: bash

    # Build the SDK
    - run: pnpm build
      shell: bash

    # Run the TS SDK tests against testnet.
    - uses: nick-fields/retry@7f8f3d9f0f62fe5925341be21c2e8314fd4f7c7c # pin@v2
      name: sdk-pnpm-test
      env:
        TMPDIR: ${{ runner.temp }}
        MOVEMENT_NETWORK: testnet
      with:
        max_attempts: 3
        timeout_minutes: 25
        # This runs all the tests, both unit and e2e.
        command: pnpm run test
