name: "Run SDK E2E tests"
description: |
  Run the SDK E2E tests against localnet

runs:
  using: composite
  steps:
    # Install node and pnpm.
    - uses: actions/setup-node@v4
      with:
        node-version-file: .node-version
        registry-url: "https://registry.npmjs.org"
    - uses: pnpm/action-setup@v4

    # Install Movement CLI for localnet
    - name: Install Movement CLI
      shell: bash
      run: |
        curl -fsSL -o movement-cli.tar.gz https://github.com/movementlabsxyz/homebrew-movement-cli/releases/download/bypass-homebrew/movement-cli-l1-linux-x86_64.tar.gz
        tar -xzf movement-cli.tar.gz
        chmod +x movement
        sudo mv movement /usr/local/bin/movement
        rm movement-cli.tar.gz
        movement --version

    # Run package install. If install fails, it probably means the updated lockfile was
    # not included in the commit.
    - run: pnpm install --frozen-lockfile
      shell: bash

    # Build the SDK
    - run: pnpm build
      shell: bash

    # Run the TS SDK E2E tests against localnet.
    - uses: nick-fields/retry@7f8f3d9f0f62fe5925341be21c2e8314fd4f7c7c # pin@v2
      name: sdk-e2e-test
      env:
        TMPDIR: ${{ runner.temp }}
      with:
        max_attempts: 3
        timeout_minutes: 25
        # This runs only E2E tests.
        command: pnpm run e2e-test
